#ayu mirage

colors:
  # Default colors
  primary:
    background: '#242936'
    foreground: '#cbccc6'
    bright_foreground: '#f28779'

  # Normal colors
  normal:
    black:   '#30304D' #
    red:     '#f08778' #
    green:   '#53bf97' #
    yellow:  '#fdcc60' #
    blue:    '#60b8d6' # 
    magenta: '#ec7171' #
    cyan:    '#98e6ca' #
    white:   '#fafafa' #

  # Brightened
  bright:
    black: '#686868'
    red: '#f58c7d'
    green: '#58c49c'
    yellow: '#ffd165'
    blue: '#65bddb'
    magenta: '#f17676'
    cyan: '#9debcf'
    white: '#ffffff'

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular

  bold:
    family: FiraCode Nerd Font
    style: Bold

  italic:
    family: FiraCode Nerd Font
    style: Italic

  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic

  size: 8

background_opacity: 0.90
